/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/fish_new.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/fish_new.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.859, -1.83]} rotation={[1.445, 0, Math.PI]} scale={0.823}>
        <primitive object={nodes.Spine_01} />
        <primitive object={nodes.Fin_Left_01} />
        <primitive object={nodes.Fin_Right_01} />
        <primitive object={nodes.Dorsal_Fin_01} />
        <skinnedMesh geometry={nodes.tripo_node_1cfb91ff.geometry} material={materials.tripo_mat_1cfb91ff} skeleton={nodes.tripo_node_1cfb91ff.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/fish_new.glb')
