/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/fishanim.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/fishanim.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Fish_Armature001">
          <primitive object={nodes.Main1} />
          <skinnedMesh name="tripo_node_1cfb91ff" geometry={nodes.tripo_node_1cfb91ff.geometry} material={materials.tripo_mat_1cfb91ff} skeleton={nodes.tripo_node_1cfb91ff.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/fishanim.glb')
