/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/newfish.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/newfish.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.304, -0.344]} rotation={[1.386, 0, 0]}>
        <primitive object={nodes.Bone} />
        <primitive object={nodes.Bone003} />
        <primitive object={nodes.Bone001} />
        <skinnedMesh geometry={nodes.tripo_node_1cfb91ff.geometry} material={materials.tripo_mat_1cfb91ff} skeleton={nodes.tripo_node_1cfb91ff.skeleton} />
      </group>
      <group position={[0, -0.304, -0.344]} rotation={[1.386, 0, 0]}>
        <primitive object={nodes.Bone011} />
      </group>
    </group>
  )
}

useGLTF.preload('/newfish.glb')
